model_type: "unet"            # "deeplab" ou "segformer" ou "unet"
image_dir: "/kaggle/input/data-remap/Augmented/Images"
mask_dir: "/kaggle/input/data-remap/Augmented/Labels_remap"

num_classes: 16
batch_size: 8
num_epochs: 500
learning_rate: 0.0001
img_size: 128

device: "cuda"
output_dir: "./output"
patience: 20
save_steps: 500
